/**
 * OpenAI LLM Provider
 *
 * Uses OpenAI-compatible Chat Completions API over fetch.
 * Supports:
 *   OPENAI_API_KEY for auth
 *   OPENAI_BASE_URL for custom endpoints
 *   TIK_MODEL for model selection
 */

import type {
  ILLMProvider,
  LLMPlanResponse,
  ChatMessage,
  ChatResponse,
  LLMToolDef,
  LLMCallOptions,
} from '@tik/shared';

export function hasOpenAICredentials(): boolean {
  return !!process.env.OPENAI_API_KEY;
}

type OpenAIMessage = {
  role: 'system' | 'user' | 'assistant' | 'tool';
  content?: string;
  tool_call_id?: string;
  tool_calls?: Array<{
    id: string;
    type: 'function';
    function: {
      name: string;
      arguments: string;
    };
  }>;
};

type OpenAITool = {
  type: 'function';
  function: {
    name: string;
    description: string;
    parameters: Record<string, unknown>;
  };
};

export class OpenAILLMProvider implements ILLMProvider {
  name = 'openai';
  private readonly apiKey: string;
  private readonly baseURL: string;
  private readonly model: string;

  constructor(model = 'gpt-4.1') {
    const apiKey = process.env.OPENAI_API_KEY;
    if (!apiKey) {
      throw new Error('OPENAI_API_KEY is required for OpenAI provider');
    }

    this.apiKey = apiKey;
    this.baseURL = (process.env.OPENAI_BASE_URL || 'https://api.openai.com/v1').replace(/\/$/, '');
    this.model = process.env.TIK_MODEL || model;
  }

  async plan(prompt: string, context: string): Promise<LLMPlanResponse> {
    const systemPrompt = [
      'You are Tik, an AI coding agent.',
      'Return only valid JSON with keys: goals, actions, reasoning.',
      'Each action must contain: tool, input, reason.',
      'Do not wrap JSON in markdown fences.',
    ].join(' ');

    const userPrompt = [
      `Task: ${prompt}`,
      '',
      'Project Context:',
      context.slice(0, 30000),
    ].join('\n');

    const response = await this.createChatCompletion({
      messages: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: userPrompt },
      ],
      responseFormatJson: true,
    });

    const content = this.extractText(response);
    const parsed = this.parseJsonResponse(content);

    return {
      goals: Array.isArray(parsed.goals) ? parsed.goals.map(String) : ['Execute the task'],
      actions: Array.isArray(parsed.actions)
        ? parsed.actions.map((action: any) => ({
            tool: String(action.tool || 'read_file'),
            input: typeof action.input === 'object' && action.input ? action.input : {},
            reason: String(action.reason || ''),
          }))
        : [],
      reasoning: String(parsed.reasoning || content || 'Generated by OpenAI provider'),
    };
  }

  async complete(prompt: string, _options?: LLMCallOptions): Promise<string> {
    const response = await this.createChatCompletion({
      messages: [{ role: 'user', content: prompt }],
    });

    return this.extractText(response);
  }

  async chat(messages: ChatMessage[], tools?: LLMToolDef[]): Promise<ChatResponse> {
    const openAIMessages = this.toOpenAIMessages(messages);
    const response = await this.createChatCompletion({
      messages: openAIMessages,
      tools,
    });
    return this.toChatResponse(response);
  }

  async chatWithContext(
    messages: ChatMessage[],
    systemPrompt: string,
    context: string,
    tools?: LLMToolDef[],
  ): Promise<ChatResponse> {
    const openAIMessages = this.toOpenAIMessages(messages, systemPrompt, context);
    const response = await this.createChatCompletion({
      messages: openAIMessages,
      tools,
    });
    return this.toChatResponse(response);
  }

  private toOpenAIMessages(
    messages: ChatMessage[],
    systemPrompt?: string,
    context?: string,
  ): OpenAIMessage[] {
    const openAIMessages: OpenAIMessage[] = [];

    if (systemPrompt) {
      const fullSystem = context
        ? `${systemPrompt}\n\n<project-context>\n${context.slice(0, 30000)}\n</project-context>`
        : systemPrompt;
      openAIMessages.push({ role: 'system', content: fullSystem });
    } else {
      for (const msg of messages) {
        if (msg.role === 'system') {
          openAIMessages.push({ role: 'system', content: msg.content });
        }
      }
    }

    for (const msg of messages) {
      if (msg.role === 'system') continue;

      if (msg.role === 'tool') {
        openAIMessages.push({
          role: 'tool',
          content: msg.content.slice(0, 10000),
          tool_call_id: msg.toolCallId || 'unknown',
        });
        continue;
      }

      // Reconstruct assistant messages with tool_calls for API fidelity
      if (msg.role === 'assistant' && msg.toolCalls?.length) {
        openAIMessages.push({
          role: 'assistant',
          content: msg.content || undefined,
          tool_calls: msg.toolCalls.map(tc => ({
            id: tc.id,
            type: 'function' as const,
            function: {
              name: tc.name,
              arguments: JSON.stringify(tc.arguments),
            },
          })),
        });
      } else {
        openAIMessages.push({
          role: msg.role,
          content: msg.content,
        });
      }
    }

    return openAIMessages;
  }

  private async createChatCompletion(options: {
    messages: OpenAIMessage[];
    tools?: LLMToolDef[];
    responseFormatJson?: boolean;
  }): Promise<any> {
    const body: Record<string, unknown> = {
      model: this.model,
      messages: options.messages,
    };

    if (options.tools?.length) {
      body.tools = options.tools.map<OpenAITool>((tool) => ({
        type: 'function',
        function: {
          name: tool.name,
          description: tool.description,
          parameters: tool.inputSchema,
        },
      }));
      body.tool_choice = 'auto';
    }

    if (options.responseFormatJson) {
      body.response_format = { type: 'json_object' };
    }

    const response = await fetch(`${this.baseURL}/chat/completions`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${this.apiKey}`,
      },
      body: JSON.stringify(body),
    });

    if (!response.ok) {
      const errorText = await response.text();

      if (options.responseFormatJson) {
        const retryBody = { ...body };
        delete retryBody.response_format;
        const retry = await fetch(`${this.baseURL}/chat/completions`, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${this.apiKey}`,
          },
          body: JSON.stringify(retryBody),
        });
        if (retry.ok) return retry.json();
      }

      throw new Error(`OpenAI API error (${response.status}): ${errorText}`);
    }

    return response.json();
  }

  private toChatResponse(response: any): ChatResponse {
    const message = response?.choices?.[0]?.message || {};
    const toolCalls = Array.isArray(message.tool_calls)
      ? message.tool_calls.map((call: any) => ({
          id: String(call.id),
          name: String(call.function?.name || ''),
          arguments: this.parseArguments(call.function?.arguments),
        }))
      : undefined;

    const promptTokens = Number(response?.usage?.prompt_tokens || 0);
    const completionTokens = Number(response?.usage?.completion_tokens || 0);

    return {
      content: this.normalizeContent(message.content),
      toolCalls: toolCalls && toolCalls.length > 0 ? toolCalls : undefined,
      usage: {
        promptTokens,
        completionTokens,
        totalTokens: Number(response?.usage?.total_tokens || promptTokens + completionTokens),
      },
    };
  }

  private extractText(response: any): string {
    const message = response?.choices?.[0]?.message;
    return this.normalizeContent(message?.content);
  }

  private normalizeContent(content: unknown): string {
    if (typeof content === 'string') return content;
    if (Array.isArray(content)) {
      return content
        .map((part: any) => {
          if (typeof part === 'string') return part;
          if (typeof part?.text === 'string') return part.text;
          return '';
        })
        .join('');
    }
    return '';
  }

  private parseArguments(input: unknown): Record<string, unknown> {
    if (typeof input !== 'string') return {};
    try {
      const parsed = JSON.parse(input);
      return typeof parsed === 'object' && parsed ? parsed : {};
    } catch {
      return {};
    }
  }

  private parseJsonResponse(content: string): any {
    const trimmed = content.trim();
    try {
      return JSON.parse(trimmed);
    } catch {
      const match = trimmed.match(/```json\s*([\s\S]*?)```/i) || trimmed.match(/```([\s\S]*?)```/);
      if (match) {
        return JSON.parse(match[1].trim());
      }
      throw new Error('Failed to parse JSON plan from OpenAI response');
    }
  }
}
