/**
 * Task System Types
 *
 * Task is the primary unit of work in Tik.
 * Everything is task-driven, not chat-driven.
 */

import type { EnvironmentPackSelection, EnvironmentPackSnapshot } from './environment-pack.js';
import type { WorkspaceProjectWorktreeKind } from './workspace.js';

// ─── Task Status ─────────────────────────────────────────────

export type TaskStatus =
  | 'pending'
  | 'planning'
  | 'executing'
  | 'evaluating'
  | 'completed'
  | 'converged'
  | 'failed'
  | 'cancelled'
  | 'paused';

// ─── Task Model ──────────────────────────────────────────────

export interface Task {
  /** Unique task ID */
  id: string;
  /** Human-readable description */
  description: string;
  /** Current status */
  status: TaskStatus;
  /** Optional project path */
  projectPath?: string;
  /** Execution plan (generated by LLM) */
  plan?: Plan;
  /** Iteration history */
  iterations: Iteration[];
  /** Final evaluation result */
  evaluation?: EvaluationSnapshot;
  /** Max allowed iterations */
  maxIterations: number;
  /** Strategy for convergence */
  strategy: ConvergenceStrategy;
  /** Created timestamp */
  createdAt: number;
  /** Last updated timestamp */
  updatedAt: number;
  /** Environment pack bound at task creation time */
  environmentPackSnapshot?: EnvironmentPackSnapshot;
  /** Task-level selection of skills and knowledge from the bound environment pack */
  environmentPackSelection?: EnvironmentPackSelection;
  /** Workspace / execution context bound at task creation time */
  workspaceBinding?: TaskWorkspaceBinding;
}

// ─── Plan ────────────────────────────────────────────────────

export interface Plan {
  /** Plan goals */
  goals: string[];
  /** Ordered actions to execute */
  actions: PlannedAction[];
  /** Risk level */
  riskLevel: 'low' | 'medium' | 'high';
  /** Estimated complexity */
  complexity: number;
}

export interface PlannedAction {
  /** Tool to invoke */
  tool: string;
  /** Tool input */
  input: unknown;
  /** Why this action */
  reason: string;
  /** Dependencies (action indices) */
  dependsOn?: number[];
}

// ─── Iteration ───────────────────────────────────────────────

export interface Iteration {
  /** Iteration number (1-based) */
  number: number;
  /** Plan for this iteration */
  plan: Plan;
  /** Actions executed */
  executedActions: ExecutedAction[];
  /** Evaluation snapshot */
  evaluation: EvaluationSnapshot;
  /** Duration in ms */
  durationMs: number;
  /** Timestamp */
  timestamp: number;
}

export interface ExecutedAction {
  /** Tool name */
  tool: string;
  /** Input provided */
  input: unknown;
  /** Output received */
  output: unknown;
  /** Whether it succeeded */
  success: boolean;
  /** Error message if failed */
  error?: string;
  /** Execution duration */
  durationMs: number;
}

// ─── Evaluation Snapshot ─────────────────────────────────────

export interface EvaluationSnapshot {
  /** Overall fitness score (0.0 - 1.0) */
  fitness: number;
  /** Structural drift magnitude */
  drift: number;
  /** Entropy delta */
  entropy: number;
  /** Whether convergence criteria met */
  converged: boolean;
  /** Number of stable iterations */
  stableCount: number;
  /** Detailed breakdown */
  breakdown?: {
    quality: number;
    correctness: number;
    stability: number;
    complexity: number;
  };
}

// ─── Task Result ─────────────────────────────────────────────

export interface TaskResult {
  /** Task ID */
  taskId: string;
  /** Final status */
  status: TaskStatus;
  /** Total iterations executed */
  totalIterations: number;
  /** Final evaluation */
  evaluation: EvaluationSnapshot;
  /** Total duration */
  durationMs: number;
  /** Summary of what was accomplished */
  summary: string;
}

// ─── Convergence Strategy ────────────────────────────────────

export type ConvergenceStrategy = 'incremental' | 'aggressive' | 'defensive';

// ─── Task Creation Input ─────────────────────────────────────

export interface CreateTaskInput {
  description: string;
  projectPath?: string;
  maxIterations?: number;
  strategy?: ConvergenceStrategy;
  environmentPackSnapshot?: EnvironmentPackSnapshot;
  environmentPackSelection?: EnvironmentPackSelection;
  workspaceBinding?: TaskWorkspaceBinding;
}

export interface TaskWorkspaceBinding {
  workspaceRoot: string;
  workspaceName: string;
  workspaceFile?: string;
  projectName?: string;
  sourceProjectPath?: string;
  effectiveProjectPath: string;
  laneId?: string;
  worktreeKind?: WorkspaceProjectWorktreeKind | 'root';
  worktreePath?: string;
}

// ─── Human Control Commands ──────────────────────────────────

export type ControlCommand =
  | { type: 'stop' }
  | { type: 'pause' }
  | { type: 'resume' }
  | { type: 'inject_constraint'; constraint: string }
  | { type: 'change_strategy'; strategy: ConvergenceStrategy }
  | { type: 'modify_plan'; modifications: Partial<Plan> };
